### PR TITLE
build_ffmpeg.sh: Do not copy dcadec files when not needed.

### PR DESCRIPTION
**Pull request by kasper93**
- Use pushd/popd

Hi, 

Few more or less cosmetic changes so we won't diverge too much from source script in mpc-hc. I hope it is fine. I wasn't sure about naming, because most names are lowercase with `_` and some new ones are UPPERCASE without `_`. Tell me which way do you prefer.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Is this the right repo?

**Comment by Underground78** [comment]
Yes, I asked @kasper93 to upstream things that makes sense for LAV too.

**Comment by kasper93** [comment]
Damn, I did it again.

**Comment by XhmikosR** [comment]
Hehe :p

**Comment by Underground78** [comment]
My bad, I missed the point... -_-'

**Pull request closed without merging**
